name: Unity VR Android Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  build:
    name: Build Unity Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Git LFS
        uses: actions/cache@v4
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ hashFiles('**/Assets/**') }}

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Android-

      - name: Cache Gradle packages and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Ensure build folder
        run: mkdir -p Builds/Android

      - name: Apply CI manifests
        run: |
          cp Packages/manifest.ci.json Packages/manifest.json
          cp Packages/packages-lock.ci.json Packages/packages-lock.json

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true

      # Pass PR number to Unity (optional if you want the APK named in C#)
      - name: Export PR number for Unity
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          CI: true
          PR_NUMBER: ${{ github.event.pull_request.number }} # pass to Unity if needed
        with:
          targetPlatform: Android
          buildMethod: BuildScript.Execute
          buildsPath: Builds/Android
          allowDirtyBuild: true

      # Rename outputs to include PR number if Unity doesn't do it for you
      - name: Tag build files with PR number
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          for f in Builds/Android/*.apk; do
            mv "$f" "Builds/Android/$(basename "$f" .apk)_PR-${PR_NUM}.apk"
          done
          if [ -f ProjectSettings/ProjectSettings.asset ]; then
            mv ProjectSettings/ProjectSettings.asset ProjectSettings/ProjectSettings_PR-${PR_NUM}.asset
          fi
          if [ -f Packages/manifest.json ]; then
            mv Packages/manifest.json Packages/manifest_PR-${PR_NUM}.json
          fi
          if [ -f Packages/packages-lock.json ]; then
            mv Packages/packages-lock.json Packages/packages-lock_PR-${PR_NUM}.json
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build-PR-${{ github.event.pull_request.number }}
          path: Builds/Android/*_PR-${{ github.event.pull_request.number }}.apk

      - name: Upload bumped project files
        uses: actions/upload-artifact@v4
        with:
          name: bumped-files-PR-${{ github.event.pull_request.number }}
          path: |
            ProjectSettings/ProjectSettings_PR-${{ github.event.pull_request.number }}.asset
            Packages/manifest_PR-${{ github.event.pull_request.number }}.json
            Packages/packages-lock_PR-${{ github.event.pull_request.number }}.json
