name: Unity VR Android Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  build:
    name: Build Unity VR Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Step 2: Cache Library folder to speed up builds
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Step 3: Optional - Run tests if you add any later
      #- name: Run Unity Tests
        #uses: game-ci/unity-test-runner@v4
        #env:
         # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          #UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          #UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        #with:
         # githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build the project
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.51f1
          targetPlatform: Android
          buildMethod: BuildScript.Execute
          buildsPath: Builds/Android

      # Step 5: Upload the build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android
