name: Unity VR Android Build & Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  prep-meta:
    name: Prepare Meta CLI
    runs-on: ubuntu-latest
    outputs:
      ovr-cli-path: ${{ steps.ovr-path.outputs.path }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup ovr-platform-util
        id: ovr-path
        uses: RageAgainstThePixel/setup-ovr-platform-util@v1
        with:
          version: latest
      # outputs.path is set by the action
      - name: Verify CLI
        run: |
          echo "OVR CLI path: $OVR_PLATFORM_UTIL"
          $OVR_PLATFORM_UTIL --help

      - name: Upload CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ovr-cli
          path: $OVR_PLATFORM_UTIL

  build-android:
    name: Build Unity Android
    runs-on: ubuntu-latest
    needs: prep-meta
    steps:
      - name: Checkout Repository in Detached HEAD
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Checkout detached HEAD
        run: |
          git fetch --depth=1
          git checkout --detach

      # Cache Library and Gradle
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-Android-

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      # Ensure build folder
      - name: Ensure build folder exists
        run: mkdir -p Builds/Android

      # Apply CI manifests temporarily
      - name: Apply CI manifests
        run: |
          cp Packages/manifest.ci.json Packages/manifest.json
          cp Packages/packages-lock.ci.json Packages/packages-lock.json

      # Free disk space before build
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true

      # Build Unity Project
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          CI: true
        with:
          targetPlatform: Android
          buildMethod: BuildScript.Execute
          buildsPath: Builds/Android
          allowDirtyBuild: true

      # Download Meta CLI from prep job
      - name: Download Meta CLI
        uses: actions/download-artifact@v4
        with:
          name: ovr-cli
          path: ovr-cli

      # Upload Meta Quest build
      - name: Upload Meta Quest Build
        run: |
          ./ovr-cli/ovr-platform-util upload \
            --app-id ${{ secrets.META_APP_ID }} \
            --app-secret ${{ secrets.META_APP_SECRET }} \
            --build-dir Builds/Android \
            --channel ALPHA \
            --notes "Automated CI upload" \
            --age-group TEENS_AND_ADULTS \
            --draft false

      # Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android
