name: Unity VR Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  build:
    name: Build Unity VR Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure build folder exists
      - name: Ensure build folder exists
        run: mkdir -p Builds/Android

      # Step 3: Setup Unity (Personal License using secrets)
      - name: Setup Unity
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 2022.3.51f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          personal: true
          unityEmail: ${{ secrets.UNITY_EMAIL }}      # from GitHub Secrets
          unityPassword: ${{ secrets.UNITY_PASSWORD }} # from GitHub Secrets

      # Step 4: Run the Unity build script
      - name: Build Project
        run: |
          BUILD_LOG="$GITHUB_WORKSPACE/build.log"
          /opt/unity/Editor/Unity \
            -projectPath $GITHUB_WORKSPACE \
            -executeMethod BuildScript.Execute \
            -quit -batchmode -nographics \
            -logFile "$BUILD_LOG"

          # Fail workflow if Unity reported errors or exceptions
          if grep -E "(error|exception)" "$BUILD_LOG"; then
            echo "Build failed due to errors in Unity log."
            exit 1
          fi

      # Step 5: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Unity-Build
          path: Builds/Android
