name: Unity Android CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Git LFS
      - name: Pull LFS files
        run: |
          git lfs pull
          git reset --hard

      # Unity Library cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Remove Meta XR Simulator **before Unity starts**
      - name: Remove Meta XR Simulator
        run: |
          manifest="Packages/manifest.json"
          if grep -q "com.meta.xr.simulator" "$manifest"; then
            echo "Removing Meta XR Simulator from manifest..."
            sudo apt-get install -y jq
            jq 'del(.dependencies["com.meta.xr.simulator"])' "$manifest" > "$manifest.tmp"
            mv "$manifest.tmp" "$manifest"
          else
            echo "Simulator package not found in manifest"
          fi
          rm -rf Library/PackageCache/com.meta.xr.simulator* || true

      # Build Android APK
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          buildMethod: BuildScript.Execute
          buildPath: Builds/Android

      # Upload APK artifact
      - uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          path: Builds/Android/**/*.apk
