name: Unity VR Android Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  build:
    name: Build Unity VR Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure build folder exists
      - name: Ensure build folder exists
        run: mkdir -p Builds/Android

      # Step 3: Activate Unity Personal License
      - name: Activate Unity Personal License
        run: |
          printf "%s" "${{ secrets.UNITY_LICENSE }}" > unity.ulf
          /opt/unity/Editor/Unity -quit -batchmode -manualLicense unity.ulf

      # Step 4: Run the Unity build script
      - name: Build Project
        run: |
          BUILD_LOG="$GITHUB_WORKSPACE/build.log"
          /opt/unity/Editor/Unity \
            -projectPath $GITHUB_WORKSPACE \
            -executeMethod BuildScript.Execute \
            -quit -batchmode -nographics \
            -logFile "$BUILD_LOG"

          # Fail workflow if Unity reported errors or exceptions
          if grep -E "(error|exception)" "$BUILD_LOG"; then
            echo "Build failed due to errors in Unity log."
            exit 1
          fi

      # Step 5: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android
