name: Unity VR Android Build & Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository in Detached HEAD
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout detached HEAD
        run: |
          git fetch --depth=1
          git checkout --detach
      - name: Cache Git LFS
        uses: actions/cache@v4
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ hashFiles('**/Assets/**') }}

      # Cache the Unity Library folder (the most important cache)
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Android-

      # Cache Gradle dependencies and build cache
      - name: Cache Gradle packages and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Ensure build folder exists
      - name: Ensure build folder
        run: mkdir -p Builds/Android

      # Apply CI manifests temporarily
      - name: Apply CI manifests
        run: |
          cp Packages/manifest.ci.json Packages/manifest.json
          cp Packages/packages-lock.ci.json Packages/packages-lock.json
          
      # Free disk space before build
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true

      # Build Unity Project
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          CI: true
        with:
          targetPlatform: Android
          buildMethod: BuildScript.Execute
          buildsPath: Builds/Android
          allowDirtyBuild: true

      # Upload build artifacts for next job
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android

  deploy-meta:
    name: Upload to Meta Quest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Download the build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android

      # Setup ovr-platform-util
      - name: Setup ovr-platform-util
        uses: RageAgainstThePixel/setup-ovr-platform-util@v1

      # Upload to Meta Quest
      - name: Upload Meta Quest Build
        uses: RageAgainstThePixel/upload-meta-quest-build@v2
        with:
          appId: ${{ secrets.META_APP_ID }}
          appSecret: ${{ secrets.META_APP_SECRET }}
          buildDir: 'Builds/Android'
          releaseChannel: 'ALPHA'
          ageGroup: 'MIXED_AGES'
          draft: true
          releaseNotes: 'Automated CI upload'
