name: Unity Android CI 😎

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Restore Library cache
      - name: Restore Library cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-

      # Unity Android Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          buildMethod: BuildScript.Execute
          buildsPath: Builds/Android
        continue-on-error: true

      # Check for critical errors (ignore simulator)
      - name: Check build log
        run: |
          SIMULATOR_ERROR="Library/PackageCache/com.meta.xr.simulator"
          if grep -q "$SIMULATOR_ERROR" "$GITHUB_WORKSPACE/unity_build.log"; then
            echo "Simulator errors detected. Ignored."
          elif grep -i "error" "$GITHUB_WORKSPACE/unity_build.log"; then
            echo "Critical errors detected. Failing build."
            cat "$GITHUB_WORKSPACE/unity_build.log"
            exit 1
          else
            echo "Build succeeded."
          fi

      # Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build-Artifacts
          path: |
            unity_build.log
            Builds/Android/*.apk
            Builds/Android/*.obb
