name: Unity Android CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      UNITY_CI: true
      GITHUB_ACTIONS: true
      UNITY_PROJECT_PATH: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove Meta XR Simulator from manifest
        run: |
          manifest="$UNITY_PROJECT_PATH/Packages/manifest.json"
          if grep -q "com.meta.xr.simulator" "$manifest"; then
            echo "Removing Meta XR Simulator from manifest..."
            sudo apt-get install -y jq
            jq 'del(.dependencies["com.meta.xr.simulator"])' "$manifest" > "$manifest.tmp"
            mv "$manifest.tmp" "$manifest"
          else
            echo "Simulator package not found in manifest"
          fi

      - name: Remove cached simulator assemblies
        run: |
          rm -rf "$UNITY_PROJECT_PATH/Library/PackageCache/com.meta.xr.simulator*" || true

      - name: Setup Unity (Personal)
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2022.3.51f1
          android: true

      - name: Build Android APK
        run: |
          /opt/unity/Editor/Unity \
            -projectPath "$UNITY_PROJECT_PATH" \
            -quit -batchmode -nographics \
            -executeMethod BuildScript.Execute \
            -logFile "$UNITY_PROJECT_PATH/unity_build.log"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: "$UNITY_PROJECT_PATH/Builds/Android/**/*.apk"
