name: Unity VR Android Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  prep:
    name: Prepare Environment
    runs-on: ubuntu-latest
    outputs:
      build-path: ${{ steps.prepare.outputs.build-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Full history for versioning
          lfs: true        # Set to false if not using Git LFS

      - name: Ensure build folder exists
        id: prepare
        run: |
          mkdir -p Builds/Android
          echo "build-path=Builds/Android" >> $GITHUB_OUTPUT

      - name: Install Meta CLI
        run: |
          wget -q https://www.oculus.com/download_app/?id=1076686279105243 -O ovr-platform-util.zip
          unzip -o ovr-platform-util.zip -d $HOME/ovr-platform-util
          chmod +x $HOME/ovr-platform-util/ovr-platform-util
          echo "$HOME/ovr-platform-util" >> $GITHUB_PATH

  build:
    name: Build Unity VR Project
    runs-on: ubuntu-latest
    needs: prep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-Android-

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Apply CI manifests
        run: |
          echo "Applying CI manifests temporarily..."
          cp Packages/manifest.ci.json Packages/manifest.json
          cp Packages/packages-lock.ci.json Packages/packages-lock.json
          echo "CI manifests applied."

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          CI: true
        with:
          targetPlatform: Android
          buildMethod: BuildScript.Execute
          buildsPath: ${{ needs.prep.outputs.build-path }}
          allowDirtyBuild: true

  upload:
    name: Upload Build
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload Meta Quest Build
        uses: RageAgainstThePixel/upload-meta-quest-build@v2
        with:
          appId: ${{ secrets.META_APP_ID }}
          appSecret: ${{ secrets.META_APP_SECRET }}
          buildDir: 'Builds/Android'
          releaseChannel: 'ALPHA'
          ageGroup: 'TEENS_AND_ADULTS'
          draft: false
          releaseNotes: 'Automated build upload'

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android
