name: Upload to Meta Quest

on:
  workflow_run:
    workflows: ["Unity VR Android Build"]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy-meta:
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
           (github.event.workflow_run.head_branch == 'develop' || github.event.workflow_run.head_branch == 'main') }}
    name: Upload to Meta Quest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android

      - name: Setup ovr-platform-util
        uses: RageAgainstThePixel/setup-ovr-platform-util@v1

      - name: Upload Meta Quest Build
        uses: RageAgainstThePixel/upload-meta-quest-build@v2
        with:
          appId: ${{ secrets.META_APP_ID }}
          appSecret: ${{ secrets.META_APP_SECRET }}
          buildDir: 'Builds/Android'
          releaseChannel: 'ALPHA'
          ageGroup: 'MIXED_AGES'
          draft: true
          releaseNotes: 'Automated CI upload'
