name: Upload to Meta Quest

on:
  workflow_run:
    workflows:
      - Unity VR Android Build
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy-meta:
    if: ${{ github.workflow_run.conclusion == 'success' && (github.workflow_run.head_branch == 'main' || github.workflow_run.head_branch == 'develop') }}
    name: Upload to Meta Quest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android

      - name: Setup ovr-platform-util
        uses: RageAgainstThePixel/setup-ovr-platform-util@v1

      - name: Upload Meta Quest Build
        uses: RageAgainstThePixel/upload-meta-quest-build@v2
        with:
          appId: ${{ secrets.META_APP_ID }}
          appSecret: ${{ secrets.META_APP_SECRET }}
          buildDir: 'Builds/Android'
          releaseChannel: 'ALPHA'
          ageGroup: 'MIXED_AGES'
          draft: true
          releaseNotes: 'Automated CI upload'

      - name: Commit version changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -- Packages/manifest.json Packages/packages-lock.json
          git add ProjectSettings/ProjectSettings.asset Packages/manifest.json Packages/packages-lock.json
          git commit -m "Version bump and revert CI manifest swap on branch $GITHUB_REF" || echo "No changes to commit"
          git push origin HEAD:$GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
