name: Upload to Meta Quest

on:
  workflow_run:
    workflows: ["Unity VR Android Build"]
    types: [completed]

permissions:
  contents: write

jobs:
  setup-unity:
    name: Setup Unity, Version Bump, and Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Unity-Build
          path: Builds/Android

      - name: Apply CI manifests
        run: |
          cp Packages/manifest.ci.json Packages/manifest.json
          cp Packages/packages-lock.ci.json Packages/packages-lock.json

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true

      - name: Run Version Bump
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          buildMethod: MyVersionManager.VersionBump

      - name: Upload bumped project files
        uses: actions/upload-artifact@v4
        with:
          name: bumped-files
          path: |
            ProjectSettings/ProjectSettings.asset
            Packages/manifest.json
            Packages/packages-lock.json

  upload-meta:
    name: Upload to Meta Quest & Commit Version
    needs: setup-unity
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'develop')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download bumped project files
        uses: actions/download-artifact@v4
        with:
          name: bumped-files

      - name: Setup ovr-platform-util
        uses: RageAgainstThePixel/setup-ovr-platform-util@v1

      - name: Upload Meta Quest Build
        uses: RageAgainstThePixel/upload-meta-quest-build@v2
        with:
          appId: ${{ secrets.META_APP_ID }}
          appSecret: ${{ secrets.META_APP_SECRET }}
          buildDir: 'Builds/Android'
          releaseChannel: 'ALPHA'
          ageGroup: 'MIXED_AGES'
          draft: true
          releaseNotes: 'Automated CI upload'

      - name: Commit version changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          [ -f Packages/manifest.json ] && git checkout -- Packages/manifest.json || echo "manifest.json not found"
          [ -f Packages/packages-lock.json ] && git checkout -- Packages/packages-lock.json || echo "packages-lock.json not found"
          git add ProjectSettings/ProjectSettings.asset Packages/manifest.json Packages/packages-lock.json
          git commit -m "Version bump and revert CI manifest swap on branch $GITHUB_REF" || echo "No changes to commit"
          git push origin HEAD:$GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete bumped files after commit
        run: |
          rm -f ProjectSettings/ProjectSettings.asset Packages/manifest.json Packages/packages-lock.json
