name: PR Merged Upload & Cleanup

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  upload-meta:
    name: Upload to Meta Quest
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download PR Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Unity-Build-PR-${{ github.event.pull_request.number }}
          path: Builds/Android/PR-${{ github.event.pull_request.number }}

      - name: Setup ovr-platform-util
        uses: RageAgainstThePixel/setup-ovr-platform-util@v1

      - name: Upload Meta Quest Build
        uses: RageAgainstThePixel/upload-meta-quest-build@v2
        with:
          appId: ${{ secrets.META_APP_ID }}
          appSecret: ${{ secrets.META_APP_SECRET }}
          buildDir: 'Builds/Android/PR-${{ github.event.pull_request.number }}'
          releaseChannel: 'ALPHA'
          ageGroup: 'MIXED_AGES'
          draft: true
          releaseNotes: 'Automated CI upload'
