name: Version Bump

on:
  push:
  
permissions:
  contents: write
jobs:
  version-bump:
    name: Bump Unity Project Version
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Cache the Unity Library folder (the most important cache)
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Android-
      # Apply CI manifests temporarily
      - name: Apply CI manifests
        run: |
          cp Packages/manifest.ci.json Packages/manifest.json
          cp Packages/packages-lock.ci.json Packages/packages-lock.json
      # Free disk space before build
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
      # Step 2: Setup Unity (batchmode)
      - name: Setup Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildMethod: MyVersionManager.PerformVersionBump
          targetPlatform: Android
          allowDirtyBuild: true
      # Step 3: Run version bump script
      #- name: Run VersionBump Script
        #run: |
          #echo "Running Unity version bump..."
          #/opt/unity/Editor/Unity \
            #-batchmode \
            #-quit \
            #-projectPath $GITHUB_WORKSPACE \
            #-executeMethod MyVersionManager.EnsureVersion \
            #-logFile versionbump.log
        
      # Step 4: Commit and push updated version
      - name: Commit version changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ProjectSettings/ProjectSettings.asset
          git checkout -- Packages/manifest.json
          git checkout -- Packages/packages-lock.json
          git commit -m "Version bump via CI on branch $GITHUB_REF" || echo "No changes to commit"
          git push origin HEAD:$GITHUB_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
